version: '3.3'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
      - "80:80"
     volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/vhost.d/default:ro

   krakend:
     image: devopsfaith/krakend:1.2.0
     volumes:
       - ./krakend.json:/etc/krakend/krakend.json
       - ./plugins/login-plugin.so:/etc/krakend/plugins/login-plugin.so
       - ./plugin.json:/etc/krakend/plugins/plugin-conf.json
       - ./service.json:/etc/krakend/config/settings/service.json
     environment:
        - FC_ENABLE=1
        - FC_SETTINGS=/etc/krakend/config/settings
        #- FC_PARTIALS=/etc/krakend/config/partials
        #- FC_TEMPLATES=/etc/krakend/config/templates
     expose:
       - 8080
     command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]

   gateway:
     image: jwilder/whoami
     environment:
      - VIRTUAL_HOST=*.ngrok.io

   swagger:
     image: swaggerapi/swagger-ui
     volumes:
       - ./openapi.json:/app/swagger.json
     environment:
       - BASE_URL=/swagger
       - SWAGGER_JSON=/app/swagger.json
     expose:
       - 8080
