version: '3.3'

services:
   krakend:
     image: devopsfaith/krakend:1.2.0
     volumes:
       - ./krakend.json:/etc/krakend/krakend.json
       #- ./server/serverPlugin.so:/etc/krakend/plugins/serverPlugin.so
       #- ./client/clientPlugin.so:/etc/krakend/plugins/clientPlugin.so
       - ./plugin/plugin.so:/etc/krakend/plugins/plugin.so
       - ./plugin.json:/etc/krakend/plugins/plugin-conf.json
     #  - ${PWD}/localhost.pem:/etc/krakend/cert.pem
     #  - ${PWD}/localhost-key.pem:/etc/krakend/key.pem
     #   "tls": {
     #    "public_key": "/etc/krakend/cert.pem",
     #    "private_key": "/etc/krakend/key.pem"
     #   },
     ports:
       - 8080:8080
     command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]

