version: '3.3'

services:
   krakend:
     image: devopsfaith/krakend:1.2.0
     volumes:
       - ./krakend.json:/etc/krakend/krakend.json
       - ./plugins/login-plugin.so:/etc/krakend/plugins/login-plugin.so
       - ./plugin.json:/etc/krakend/plugins/plugin-conf.json
       - ./service.json:/etc/krakend/config/settings/service.json
     environment:
        - FC_ENABLE=1
        - FC_SETTINGS=/etc/krakend/config/settings
        #- FC_PARTIALS=/etc/krakend/config/partials
        #- FC_TEMPLATES=/etc/krakend/config/templates
     ports:
       - 8080:8080
     command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
